# Intuitions & Computational Insights

In [92]:
import numpy as np


## Hadamard Product
numpy's np.multiply() function returns the Hadamard Product (element-wise). 

The * operator can be used as a shorthand for np.multiply on ndarrays. 

**Don't confuse it for matrix multiplication operation**

In [114]:
A = np.array([[1, 2, 3],
              [0, 1, 0]])
B = np.array([[1, 0, 1], 
              [0, 1, 1]])
print("A*B: ") 
print(A*B)

A*B: 
[[1 0 3]
 [0 1 0]]


# Norms

Formally, $L_p$ norm is defined as:
$$\|\boldsymbol{x}\|_p=\left(\sum_i\left|x_i\right|^p\right)^{\frac{1}{p}}$$


## $L_1$ Norm
The $L_1$ norm is commonly used in machine learning when the difference between zero and nonzero elements is very important. Every time an element of x moves away from 0 by $\epsilon$, the $L_1$ norm increases by $\epsilon$.

In [94]:
# L_1 norm for vectors
a = np.array([1, 0, 2])
print("a: ")
print(a)
l1norm = (sum(list(map(lambda n: n, np.nditer(a)))))
print("L1 norm of a, l1norm = " + str(l1norm))
print("np.linalg.norm(a, ord=1) == l1norm: " + str(np.linalg.norm(a, ord=1) == l1norm))


a: 
[1 0 2]
L1 norm of a, l1norm = 3
np.linalg.norm(a, ord=1) == l1norm: True


## $L_2$ Norm
The $L_2$ norm is known as the Euclidean norm, which is simply the Euclidean distance from the origin to the point identified by x. 

Denoted simply as $||x||$ with the subscript 2 omitted. 

Numpy's np.linalg.norm() function defaults to $L_2$ norm for vectors and Frobenius norm for matricies

## Frobenius Norm
$$\|A\|_F=\sqrt{\sum_{i, j} A_{i, j}^2}$$

In [95]:
# numpy defaults to L_2 norm for vectors
b = np.array([1, 0, 2])
print("b: ")
print(b)
l2norm = (sum(list(map(lambda n: n ** 2, np.nditer(b))))**0.5)
print("L2 norm of b, l2norm = " + str(l2norm))
print("np.linalg.norm(b) == l2norm: " + str(np.linalg.norm(b) == l2norm))
print("\n")

# numpy defaults to Frobenius norm for matricies
M = np.array([[1, 2, 3],
              [0, 1, 0]])
print("M: ")
print(M)
frnorm = (sum(list(map(lambda n: n ** 2, np.nditer(M))))**0.5)
print("Fronebius norm of M, frnorm = " + str(frnorm))
print("np.linalg.norm(M) == frnorm: "+str(np.linalg.norm(M) == frnorm))


b: 
[1 0 2]
L2 norm of b, l2norm = 2.23606797749979
np.linalg.norm(b) == l2norm: True


M: 
[[1 2 3]
 [0 1 0]]
Fronebius norm of M, frnorm = 3.872983346207417
np.linalg.norm(M) == frnorm: True


It is also common to measure the size of a vector using the **squared** $L_2$ norm, which can be calculated simply as $x^Tx$.

In [96]:
print("Squared L2 norm of b, or b transpose b: " + str(b.T.dot(b)))
print("np.isclose(np.linalg.norm(b)**2, b.T.dot(b)): " +
      str(np.isclose(np.linalg.norm(b)**2, b.T.dot(b))))


Squared L2 norm of b, or b transpose b: 5
np.isclose(np.linalg.norm(b)**2, b.T.dot(b)): True


## "$L_0$ Norm"
We sometimes measure the size of the vector by counting its number of nonzero elements. Some authors refer to this function as the “$L_0$ norm,” but this is incorrect terminology. The number of nonzero entries in a vector is not a norm, because scaling the vector by $α$ does not change the number of nonzero entries. The $L_0$ norm is often used as a substitute for the number of nonzero entries.

In [113]:
# numpy norm function with ord=0 gives L_0 norm for vectors
print("b: ")
print(b)
l0norm_b = (sum(list(map(lambda n: 1 if n != 0 else 0, np.nditer(b)))))
print("L0 norm of b, l0norm_b = " + str(l0norm_b))
print("np.linalg.norm(b, ord=0) == l0norm_b: " +
      str(np.linalg.norm(b, ord=0) == l0norm_b))

print('\n')

print("M: ")
print(M)
l0norm_M = (sum(list(map(lambda n: 1 if n != 0 else 0, np.nditer(M)))))
print("L0 norm of M, l0norm_M = " + str(l0norm_M))
# however is undefined for matricies
try:
    print("np.linalg.norm(M, ord=0) == l0norm_M: " +
      str(np.linalg.norm(M, ord=0) == l0norm_M))
except Exception as e:
    print(e)
    
print("\n")


b: 
[1 0 2]
L0 norm of b, l0norm_b = 2
np.linalg.norm(b, ord=0) == l0norm_b: True


M: 
[[1 2 3]
 [0 1 0]]
L0 norm of M, l0norm_M = 4
Invalid norm order for matrices.


