## Intuitions & Computational Insights

In [22]:
import numpy as np


### Hadamard Product
numpy's np.multiply() function returns the Hadamard Product (element-wise). 

The * operator can be used as a shorthand for np.multiply on ndarrays. 

**Don't confuse it for matrix multiplication operation**

In [23]:
A = np.array([[1, 2, 3],
              [0, 1, 0]])
B = np.array([[1, 0, 1], 
              [0, 1, 1]])
print("A*B: ") 
A*B

A*B: 


array([[1, 0, 3],
       [0, 1, 0]])

### Norms

Formally, $L_p$ norm is defined as:
$$\|\boldsymbol{x}\|_p=\left(\sum_i\left|x_i\right|^p\right)^{\frac{1}{p}}$$


The $L_1$ norm is commonly used in machine learning when the difference between zero and nonzero elements is very important. Every time an element of x movesaway from 0 by $\epsilon$, the $L_1$ norm increases by $\epsilon$.

The $L_2$ norm is known as the Euclidean norm, which is simply the Euclidean distance from the origin to the point identified by x. 

Denoted simply as $||x||$ with the subscript 2 omitted. 

Numpy's np.linalg.norm() function defaults to $L_2$ norm for vectors and Frobenius norm for matricies

Frobenius norm:
$$\|A\|_F=\sqrt{\sum_{i, j} A_{i, j}^2}$$

In [70]:
# numpy defaults to L_2 norm for vectors
B = np.array([1, 0, 2])
print("B: ")
print(B)
l2norm = (sum(list(map(lambda n: n ** 2, np.nditer(B))))**0.5)
print("L2 norm of B, l2norm = " + str(l2norm))
print("np.linalg.norm(B) == l2norm: " + str(np.linalg.norm(B) == l2norm))
print("\n")

# numpy defaults to Frobenius norm for matricies
M = np.array([[1, 2, 3],
              [0, 1, 0]])
print("M: ")
print(M)
frnorm = (sum(list(map(lambda n: n ** 2, np.nditer(M))))**0.5)
print("Fronebius norm of M, frnorm = " + str(frnorm))
print("np.linalg.norm(M) == frnorm: "+str(np.linalg.norm(M) == frnorm))


B: 
[1 0 2]
L2 norm of B, l2norm = 2.23606797749979
np.linalg.norm(B) == l2norm: True


M: 
[[1 2 3]
 [0 1 0]]
Fronebius norm of M, frnorm = 3.872983346207417
np.linalg.norm(M) == frnorm: True


It is also common to measure the size of a vectorusing the **squared** $L_2$ norm, which can be calculated simply as $x^Tx$.

In [71]:
print("Squared L2 norm of B, or B transpose B: " + str(B.T.dot(B)))
print("np.isclose(np.linalg.norm(B)**2, B.T.dot(B)): " +
      str(np.isclose(np.linalg.norm(B)**2, B.T.dot(B))))


Squared L2 norm of B, or B transpose B: 5
np.isclose(np.linalg.norm(B)**2, B.T.dot(B)): True
